version: '3.9'

services:
  backend:
    build: .
    container_name: teacorner-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres
    networks:
      - teacorner-network

  postgres:
    image: postgres:16
    container_name: teacorner-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tea_corner
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - teacorner-network

networks:
  teacorner-network:

volumes:
  pgdata:
